build: couple of fixes for ng test under bazel
This doesn't get us green but at least we are now a step closer

Current error
```
Nov  4 17:30:07  Google Chrome Helper (Renderer)[75527] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
Nov  4 17:30:07  Google Chrome Helper (Renderer)[75526] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
2019-11-04 17:30:16.932 Google Chrome[75501:581298] KSPaths could not set subdirectory permissions. [com.google.Keystone.SharedErrorDomain:1003 - '/Users/alan/Library/Google' - 'KSPaths.m:636'] (The operation couldn’t be completed. Operation not permitted [NSPOSIXErrorDomain:1])
2019-11-04 17:30:16.932 Google Chrome[75501:581298] KSBundle could not obtain user bundle path. [com.google.Keystone.SharedErrorDomain:1201 - 'KSBundle.m:44'] (KSPaths could not set subdirectory permissions. - '/Users/alan/Library/Google' [com.google.Keystone.SharedErrorDomain:1003])
2019-11-04 17:30:16.933 Google Chrome[75501:581298] KSPaths could not set subdirectory permissions. [com.google.Keystone.SharedErrorDomain:1003 - '/Users/alan/Library/Google' - 'KSPaths.m:636'] (The operation couldn’t be completed. Operation not permitted [NSPOSIXErrorDomain:1])
2019-11-04 17:30:16.933 Google Chrome[75501:581298] KSBundle could not obtain user bundle path. [com.google.Keystone.SharedErrorDomain:1201 - 'KSBundle.m:44'] (KSPaths could not set subdirectory permissions. - '/Users/alan/Library/Google' [com.google.Keystone.SharedErrorDomain:1003])
Nov  4 17:30:19  Google Chrome Helper (Renderer)[75558] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
Nov  4 17:30:19  Google Chrome Helper (Renderer)[75559] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
Nov  4 17:30:19  Google Chrome Helper (Renderer)[75561] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
Nov  4 17:30:19  Google Chrome Helper (Renderer)[75563] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
Nov  4 17:30:19  Google Chrome Helper (Renderer)[75564] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
Nov  4 17:30:19  Google Chrome Helper (Renderer)[75565] <Error>: SeatbeltExecServer: Failed to initialize sandbox: -1 Operation not permitted
Failed to initialize sandbox.
[75501:37379:1104/173019.552923:FATAL:gpu_data_manager_impl_private.cc(986)] The display compositor is frequently crashing. Goodbye.

FAILURE
Result: {
    "success": false,
    "target": {
        "project": "frontend",
        "target": "test"
    }
}

Logs:
frontend:test:
ERROR in error TS2688: Cannot find type definition file for 'jasmine'.
error TS2688: Cannot find type definition file for 'node'.
src/app/app.component.spec.ts:1:32 - error TS2307: Cannot find module '@angular/core/testing'.

1 import { TestBed, async } from '@angular/core/testing';
                                 ~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.component.spec.ts:2:37 - error TS2307: Cannot find module '@angular/router/testing'.

2 import { RouterTestingModule } from '@angular/router/testing';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~
src/app/app.component.spec.ts:5:1 - error TS2593: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha` and then add `jest` or `mocha` to the types field in your tsconfig.

5 describe('AppComponent', () => {
  ~~~~~~~~
src/app/app.component.spec.ts:6:3 - error TS2304: Cannot find name 'beforeEach'.

6   beforeEach(async(() => {
    ~~~~~~~~~~
src/app/app.component.spec.ts:17:3 - error TS2593: Cannot find name 'it'. Do you need to install type definitions for a test runner? Try `npm i @types/jest` or `npm i @types/mocha` and then add `jest` or `mocha` to the types field in your tsconfig.

```